mail.server.protocol=imap

mail.server.host=imap.gmail.com
mail.server.port=993

mail.username=solvd.olesya@gmail.com
mail.password=hdhqzcbxorykjtet

mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
